name: 'Deploy Lambda Function'
description: 'Deploys Lambda functions using a custom script'
author: 'Mohamed Navfar'

inputs:
  ALIAS_NAME:
    description: 'Alias Name'
    required: false
  ARTIFACT_BUCKET:
    description: 'Artifact S3 Bucket Name'
    required: true
  ARTIFACT_PATH:
    description: 'S3 Path of the Artifact'
    required: true
  LAMBDA_CONFIG_FILE:
    description: 'Path to Lambda Config File'
    required: true
  PUBLISH:
    description: 'Publish Flag'
    required: false

runs:
  using: 'docker'
  image: "Dockerfile"

branding:
  icon: "layers"
  color: "gray-dark"